@startuml
package internal\pkg\mat{
annotation internal\pkg\mat {
-const EPSILON: FLOAT

+AlmostEqualFloat64(a float64, b float64): bool
+NewPoint(x float64, y float64, z float64): *Tuple4
+NewVector(x float64, y float64, z float64): *Tuple4
+NewTuple4(x float64, y float64, z float64, w float64): *Tuple4
+NewEmptyTuple4(): *Tuple4
+Add(t1 Tuple4, t2 Tuple4): *Tuple4
+Sub(t1 Tuple4, t2 Tuple4): *Tuple4
+Negate(t Tuple4): *Tuple4
+MultiplyByScalar(t Tuple4, scalar float64): *Tuple4
+DivideByScalar(t Tuple4, scalar float64): *Tuple4
+Magnitude(t Tuple4): float64
+Normalize(t Tuple4): *Tuple4
+TupleEquals(t1 Tuple4, t2 Tuple4): bool
+Dot(t1 Tuple4, t2 Tuple4): float64
+Cross(t1 Tuple4, t2 Tuple4): *Tuple4
}
class Tuple4 {
+Data: []float64
+IsPoint(): bool
+IsVector(): bool
+Get(row int): float64
+GetX(): float64
+GetY(): float64
+GetZ(): float64
+GetW(): float64
}
}
package .{
annotation . {


-main()
}
}


@enduml